# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comms_pb2 as comms__pb2


class SmartHomeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Command = channel.unary_unary(
                '/SmartHomeService/Command',
                request_serializer=comms__pb2.sendCommandToDevice.SerializeToString,
                response_deserializer=comms__pb2.receiveResponse.FromString,
                )


class SmartHomeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartHomeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=comms__pb2.sendCommandToDevice.FromString,
                    response_serializer=comms__pb2.receiveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SmartHomeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SmartHomeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartHomeService/Command',
            comms__pb2.sendCommandToDevice.SerializeToString,
            comms__pb2.receiveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
